### ISSUE TITLE
Never exits when export is complete

### ISSUE THREAD

**Issue by tadhgboyle** [allquixotic/encuum-kt#2]
Hey there 👋🏼 
Thanks for this, really helpful for archiving and for migrating to different forum software.

I exported a decently large enjin site today - it took about 2 hours.
During the 2 hours the `forum.db` file was being modified every 30 seconds or so with new data.

Eventually, it stopped modifying the file and nothing was printed to the console for about 5 minutes, so I ctrl-c'd - I assume it was fully done.

Is there any way for us to get a message and perhaps for it to automatically stop running when the export is complete, or will it do that already and I just was too impatient 😛 ?

Screenshot for the current time, time the file was last modified and the running script:
<img width="500" alt="Screenshot 2023-01-17 at 15 36 10" src="https://user-images.githubusercontent.com/26070412/213035717-c32c5321-daed-4d4e-b22d-7f40cac6bdef.png">

Thank you

**Comment by allquixotic** [comment]
I believe this problem no longer exists in the new version of encuum here: https://github.com/allquixotic/encuum . Please check it out.
