### ISSUE TITLE
TimeOut Error

### ISSUE THREAD

**Issue by sarhatabaot** [allquixotic/encuum-kt#3]
I'm getting a timeout error when running the tool:
```
Exception in thread "main" com.microsoft.playwright.TimeoutError: Error {
  message='Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator("[name=username]")
```

I'm thinking this is because I have 2FA enabled. Unsure.

**Comment by allquixotic** [comment]
Yes, encuum does not currently support 2FA. You should disable it on your account if possible. I'm still working on a tool that will use the Enjin API instead of screen scraping if you would prefer to wait for that.

**Comment by sarhatabaot** [comment]
Still experiencing this issue. 
I disabled 2FA just in case. It seems it's stuck for me on the "redirecting" page. I'll wait for the API tool :)

**Comment by sarhatabaot** [comment]
Changing the playwright browser type to firefox fixed this issue for me!
