### ISSUE TITLE
Only scrape from a specific subforum?

### ISSUE THREAD

**Issue by AvrikV** [allquixotic/encuum-kt#4]
Is it possible to implement this? I would like to archive a certain subforum but have no need for the others, which have thousands of threads. Would be really helpful if this could be added somehow. Either way, thanks so much for this tool.

**Comment by allquixotic** [comment]
Absolutely, yes, this is a feature I also desire. I'm working on Encuum related stuffs this weekend and next. I know we're up against the April deadline, so my goal is to get a very good, stable, efficient version of Encuum working by end of February or early March. It would be sooner, but I have a full-time RL job and I help manage a big guild in an MMO.

I'll make sure to communicate to my fellow Enjin-platform-using friends on the forums and in my GitHub Repo when I make major milestone progress on my tools.

**Comment by AvrikV** [comment]
Sounds great! I only just heard about Enjin shutting down soon so this is a lifesaver. Real shame all of these old MMO community and guild sites are just going to go poof soon.

**Comment by allquixotic** [comment]
I'm going to be working on this feature in the new version of encuum here: https://github.com/allquixotic/encuum . Please check it out.
